services:
  research-env:
    build: .
    container_name: iot-ids-research
    user: "${UID:-1000}:${GID:-1000}"  # ← ADICIONAR
    ports:
      - "8888:8888"  # Jupyter Lab
      - "5000:5000"  # MLflow
    volumes:
      - .:/workspace
      - /tmp/dvc-remote:/tmp/dvc-remote  # DVC remote
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - USER=researcher
      - GROUP=researcher
      - JUPYTER_ENABLE_LAB=yes
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - HOME=/workspace
      - JUPYTER_CONFIG_DIR=/workspace/.jupyter
      - JUPYTER_DATA_DIR=/workspace/.local/share/jupyter
      - JUPYTER_RUNTIME_DIR=/workspace/.local/share/jupyter/runtime
    command: ["with-mlflow", "jupyter", "lab", "--config=/workspace/.jupyter/jupyter_lab_config.py"]
    
  # Opcional: banco de dados para MLflow em produção
  mlflow-db:
    image: postgres:13
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: