stages:
  check_quality:
    cmd: python3 dvc_run_quality_check.py
    deps:
    - dvc_run_quality_check.py
    - check_dataset_quality.py
    outs:
    - data/metrics/quality_check.json
  sampling:
    cmd: python3 dvc_sampling.py
    deps:
    - data/raw/CSV/MERGED_CSV
    - dvc_sampling.py
    outs:
    - data/processed/sampled.csv
  eda:
    cmd: python3 src/eda/dvc_eda.py
    deps:
    - data/processed/sampled.csv
    - src/eda/dvc_eda.py
    outs:
    - src/eda/results/
  preprocess:
    cmd: python3 dvc_preprocessing.py
    deps:
    - data/processed/sampled.csv
    - dvc_preprocessing.py
    - configs/preprocessing.yaml
    outs:
    - data/processed/train_normalized.csv
    - data/processed/test_normalized.csv
    - data/processed/scaler.pkl
    - data/processed/X_train.npy
    - data/processed/X_test.npy
    - data/processed/y_train.npy
    - data/processed/y_test.npy
    - data/processed/preprocessing_metadata.json
    - data/processed/binary/train_binary.csv
    - data/processed/binary/test_binary.csv
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/scaler.pkl
    - data/processed/binary/binary_metadata.json
  # === EXPERIMENTOS INDIVIDUAIS - MODO TESTE ===
  exp_test_isolation_forest:
    cmd: python3 experiments/run_single_algorithm.py isolation_forest
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results_test/isolationforest/
    - experiments/logs_test/IsolationForest/
    
  exp_test_one_class_svm:
    cmd: python3 experiments/run_single_algorithm.py one_class_svm
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results_test/oneclasssvm/
    - experiments/logs_test/OneClassSVM/
    
  exp_test_random_forest:
    cmd: python3 experiments/run_single_algorithm.py random_forest
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results_test/randomforestclassifier/
    - experiments/logs_test/RandomForestClassifier/
    
  exp_test_logistic_regression:
    cmd: python3 experiments/run_single_algorithm.py logistic_regression
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results_test/logisticregression/
    - experiments/logs_test/LogisticRegression/

  exp_test_svc:
    cmd: python3 experiments/run_single_algorithm.py svc
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results_test/svc/
    - experiments/logs_test/SVC/
    
  # === CONSOLIDAÇÃO TESTE ===
  consolidate_test_results:
    cmd: python3 experiments/consolidate_results.py
    deps:
    - experiments/consolidate_results.py
    - experiments/results_test/isolationforest/
    - experiments/results_test/oneclasssvm/
    - experiments/results_test/randomforestclassifier/
    - experiments/results_test/logisticregression/
    - experiments/results_test/svc/
    outs:
    - experiments/final_results_test/
    - experiments/final_plots_test/
    - experiments/final_tables_test/
    - experiments/final_report_test/

  # === EXPERIMENTOS INDIVIDUAIS - MODO COMPLETO ===
  exp_isolation_forest:
    cmd: python3 experiments/run_single_algorithm.py isolation_forest
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/isolationforest/
    - experiments/logs/IsolationForest/
    
  exp_one_class_svm:
    cmd: python3 experiments/run_single_algorithm.py one_class_svm
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/oneclasssvm/
    - experiments/logs/OneClassSVM/
    
  exp_local_outlier_factor:
    cmd: python3 experiments/run_single_algorithm.py local_outlier_factor
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/localoutlierfactor/
    - experiments/logs/LocalOutlierFactor/
    
  exp_elliptic_envelope:
    cmd: python3 experiments/run_single_algorithm.py elliptic_envelope
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/ellipticenvelope/
    - experiments/logs/EllipticEnvelope/
    
  exp_random_forest:
    cmd: python3 experiments/run_single_algorithm.py random_forest
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/randomforestclassifier/
    - experiments/logs/RandomForestClassifier/
    
  exp_logistic_regression:
    cmd: python3 experiments/run_single_algorithm.py logistic_regression
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/logisticregression/
    - experiments/logs/LogisticRegression/
    
  exp_gradient_boosting:
    cmd: python3 experiments/run_single_algorithm.py gradient_boosting
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/gradientboostingclassifier/
    - experiments/logs/GradientBoostingClassifier/
    
  # === CONSOLIDAÇÃO FINAL ===
  consolidate_results:
    cmd: python3 experiments/consolidate_results.py
    deps:
    - experiments/consolidate_results.py
    - experiments/results/isolationforest/
    - experiments/results/oneclasssvm/
    - experiments/results/localoutlierfactor/
    - experiments/results/ellipticenvelope/
    - experiments/results/randomforestclassifier/
    - experiments/results/logisticregression/
    - experiments/results/gradientboostingclassifier/
    outs:
    - experiments/final_results/
    - experiments/final_plots/
    - experiments/final_tables/
    - experiments/final_report/
