stages:
  check_quality:
    cmd: python3 dvc_run_quality_check.py
    deps:
    - dvc_run_quality_check.py
    - check_dataset_quality.py
    outs:
    - data/metrics/quality_check.json
  sampling:
    cmd: python3 dvc_sampling.py
    deps:
    - data/raw/CSV/MERGED_CSV
    - dvc_sampling.py
    outs:
    - data/processed/sampled.csv
  eda:
    cmd: python3 src/eda/dvc_eda.py
    deps:
    - data/processed/sampled.csv
    - src/eda/dvc_eda.py
    outs:
    - src/eda/results/
  preprocess:
    cmd: python3 dvc_preprocessing.py
    deps:
    - data/processed/sampled.csv
    - dvc_preprocessing.py
    - configs/preprocessing.yaml
    outs:
    - data/processed/train_normalized.csv
    - data/processed/test_normalized.csv
    - data/processed/scaler.pkl
    - data/processed/X_train.npy
    - data/processed/X_test.npy
    - data/processed/y_train.npy
    - data/processed/y_test.npy
    - data/processed/preprocessing_metadata.json
    - data/processed/binary/train_binary.csv
    - data/processed/binary/test_binary.csv
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/scaler.pkl
    - data/processed/binary/binary_metadata.json

  # === EXPERIMENTOS INDIVIDUAIS ===
  # Os estágios se adaptam automaticamente ao TEST_MODE do algorithm_comparison.py
  
  exp_isolation_forest:
    cmd: python3 experiments/run_single_algorithm.py isolation_forest
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/
    - experiments/logs/IsolationForest/
    
  exp_one_class_svm:
    cmd: python3 experiments/run_single_algorithm.py one_class_svm
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/
    - experiments/logs/OneClassSVM/
    
  exp_random_forest:
    cmd: python3 experiments/run_single_algorithm.py random_forest
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/
    - experiments/logs/RandomForestClassifier/
    
  exp_logistic_regression:
    cmd: python3 experiments/run_single_algorithm.py logistic_regression
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/
    - experiments/logs/LogisticRegression/

  exp_svc:
    cmd: python3 experiments/run_single_algorithm.py svc
    deps:
    - experiments/run_single_algorithm.py
    - experiments/algorithm_comparison.py
    - data/processed/binary/X_train_binary.npy
    - data/processed/binary/X_test_binary.npy
    - data/processed/binary/y_train_binary.npy
    - data/processed/binary/y_test_binary.npy
    - data/processed/binary/binary_metadata.json
    outs:
    - experiments/results/
    - experiments/logs/SVC/

  # === CONSOLIDAÇÃO DE RESULTADOS ===
  # Consolida os resultados de todos os algoritmos
  consolidate_results:
    cmd: python3 experiments/consolidate_results.py
    deps:
    - experiments/consolidate_results.py
    - experiments/results/
    outs:
    - experiments/final_results/
    - experiments/final_plots/
    - experiments/final_tables/
    - experiments/final_report/